import assert from 'node:assert/strict';
import {join} from 'node:path';
import {ROOT,run,readJSON,fitFrame,sha} from '../scripts/lib.mjs';
import {prepare,finish,soundPolicy,selectImageProvider,validateImageProvenance} from '../scripts/plog.mjs';
import {createScene} from '../scripts/create-scene.mjs';
import {photoPrompt,photoRequest} from '../scripts/photo-prompt.mjs';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
const rows=[],pass=(name)=>rows.push({name,passed:true});
const codexEnv={CODEX_THREAD_ID:'test-thread'},otherEnv={};
assert.throws(()=>selectImageProvider({},otherEnv),/实际工具名/);
assert.deepEqual(selectImageProvider({},codexEnv),{host:'codex',tool:'image_gen.imagegen'});
assert.throws(()=>selectImageProvider({'image-host':'other','image-tool':'test.photo_edit'},codexEnv),/当前在 Codex/);
assert.deepEqual(selectImageProvider({'image-tool':'test.photo_edit'},otherEnv),{host:'other',tool:'test.photo_edit'});
assert.throws(()=>selectImageProvider({'image-host':'codex'},otherEnv),/不在 Codex/);
assert.throws(()=>selectImageProvider({'image-host':'other'},otherEnv),/实际工具名/);
assert.throws(()=>selectImageProvider({'image-host':'invalid'},otherEnv),/图片处理环境/);
const otherProvider=selectImageProvider({'image-host':'other','image-tool':'test.photo_edit'},otherEnv);
const otherRecord={host:'other',tool:'test.photo_edit',toolCallId:'test-only-not-a-real-generation'};
assert.deepEqual(validateImageProvenance(otherProvider,otherRecord,otherEnv),otherProvider);
assert.throws(()=>validateImageProvenance(otherProvider,otherRecord,codexEnv),/当前在 Codex/);
assert.throws(()=>validateImageProvenance(otherProvider,{...otherRecord,tool:'different.tool'},otherEnv),/所选工具/);
assert.throws(()=>validateImageProvenance(otherProvider,{...otherRecord,host:undefined},otherEnv),/环境与任务/);
assert.throws(()=>validateImageProvenance(otherProvider,{...otherRecord,toolCallId:' '},otherEnv),/真实调用标识/);
assert.throws(()=>validateImageProvenance(undefined,otherRecord,otherEnv),/实际工具名/);
assert.deepEqual(validateImageProvenance(undefined,{tool:'image_gen.imagegen',toolCallId:'test-only'},codexEnv),{host:'codex',tool:'image_gen.imagegen'});
pass('生图环境默认随宿主判定、平台环境须绑定实际工具、Codex 禁止外部降级与旧任务兼容；未调用外部生图');
const p1=await photoPrompt('A quiet pause.'),p2=await photoPrompt('A slow morning.');
assert.equal(p1.templateSha256,p2.templateSha256);
assert.equal(p1.prompt.replace('A quiet pause.','A slow morning.'),p2.prompt);
const request=await photoRequest('/input/photo.jpg','A quiet pause.',{host:'codex',tool:'image_gen.imagegen'});
assert.deepEqual(request.referenced_image_paths,['/input/photo.jpg']);
assert.equal(request.prompt,p1.prompt);
assert(!existsSync(join(ROOT,'audio')));assert(!existsSync(join(ROOT,'frozen/quiet-food')));
pass('纯提示词一致且只传原图，旧音效和参考图目录已移除');
const captionDirectory=await mkdtemp(join(tmpdir(),'plog-test-caption-'));
try {
 const captionJob={photo:'unused-photo.jpg',mode:'style',out:join(captionDirectory,'job')};
 for(const text of [undefined,'','   '])await assert.rejects(prepare({...captionJob,caption:text}),/按本图语义.*--caption/);
 assert(!existsSync(captionJob.out),'缺少文案时不得生成任务目录或自动套用固定句子');
} finally {await rm(captionDirectory,{recursive:true,force:true});}
pass('新增英文前必须传入看图生成的短句；漏传或空文案时不创建任务、不使用固定默认文案');
assert.equal(soundPolicy(), 'original');assert.equal(soundPolicy('mute'),'mute');assert.throws(()=>soundPolicy('candidate'),/声音策略/);
await assert.rejects(prepare({sound:'candidate'}),/声音策略/);
const rejectedJob=await mkdtemp(join(tmpdir(),'plog-test-sound-'));
try {await writeFile(join(rejectedJob,'job.json'),JSON.stringify({sound:'candidate'}));await assert.rejects(finish({job:rejectedJob}),/声音策略/);assert(!existsSync(join(rejectedJob,'output')))}finally{await rm(rejectedJob,{recursive:true,force:true})}
pass('准备和导出均拒绝旧候选音效任务；原声与静音策略保留');
const catalog=await readJSON(join(ROOT,'effects/catalog.json'));
assert.equal(catalog.length,13);assert.equal(new Set(catalog.map(x=>x.id)).size,13);
for(const id of ['puzzle','moon','glitter-petals','falling-leaves'])assert(!catalog.some(x=>x.id===id));pass('十三种模板和已删除效果边界');
for(const [w,h] of [[4000,3000],[3000,4000],[943,1257],[1200,800]]){const f=fitFrame(w,h);assert(f.width<=w&&f.height<=h);assert(!(f.width%2||f.height%2));assert(Math.abs(f.width/f.height-w/h)<=Math.max(2/f.height,2*f.width/f.height**2));}
assert.throws(()=>fitFrame(100000,64));pass('横竖图不放大、等比缩小及极端比例拒绝');
await assert.rejects(prepare({mode:'unknown'}));await assert.rejects(prepare({photo:'x.jpg',out:'x',sound:'invalid'}),/声音策略/);
await assert.rejects(createScene({effect:'puzzle'}),/未知/);await assert.rejects(createScene({effect:'snow',layout:{}}),/布局/);pass('模式、声音策略、旧效果和未经绑定布局拒绝');
const faces=await readJSON(join(ROOT,'faces/catalog.json'));assert.equal(faces.length,5);pass('五种静态表情随包携带');
console.log(JSON.stringify({rows,notVerified:['真实原Live静止/手持/带声','方向信息素材的实际显示','手机和小红书','调色和动效观感']},null,2));
